[package]
name = "rusty-chain"
version = "0.1.0"
authors = ["Damon Sweeney <me@damons.email>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.14"
rand = "0.7.3"
sha2 = "0.9.0"